name: mqgo_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core_platform_interface: 5.0.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  fluttertoast: ^8.0.8
  firebase_app_check: ^0.2.2+4
  firebase_storage: ^11.2.8
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.1
  the_apple_sign_in: ^1.1.1
  photo_view: ^0.15.0
  webview_flutter: ^2.0.13
  image_picker: ^0.8.4+4
  flutter_calendar_carousel: ^2.4.2
  flutter_dynamic_theme: ^1.0.0
  provider: ^5.0.0
  flutter_native_splash: ^1.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_native_splash: ^1.2.0
  mockito: ^5.0.11

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_native_splash:
  color: "#42a5f5"
  image: images/splash.png